config/routes.rb
Rails.application.routes.draw do

  root 'batches#index'
  resources :batches
  devise_for :users
  post "/send_data" => "welcome#send_data"
  get '/batches/:id/receiving' => "batches#receiving"
  get '/batches/:id/sending' => "batches#sending"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/batch.rb
class Batch < ApplicationRecord
  has_many :batch_users
  has_many :users, through: :batch_users
end

app/models/batch_user.rb
class BatchUser < ApplicationRecord
  belongs_to :user
  belongs_to :batch
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :batch_users
  has_many :batches, through: :batch_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  before_action :set_batch, only: [:show, :edit, :update, :destroy, :sending, :receiving]
  before_action :authenticate_user!
  # GET /batches
  # GET /batches.json
  def index
    @batches = Batch.all
  end

  # GET /batches/1
  # GET /batches/1.json
  def show
  end

  # GET /batches/new
  def new
    @batch = Batch.new
  end

  # GET /batches/1/edit
  def edit
  end

  # POST /batches
  # POST /batches.json
  def create
    @batch = Batch.new(batch_params)

    respond_to do |format|
      if @batch.save
        format.html { redirect_to @batch, notice: 'Batch was successfully created.' }
        format.json { render :show, status: :created, location: @batch }
      else
        format.html { render :new }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /batches/1
  # PATCH/PUT /batches/1.json
  def update
    respond_to do |format|
      if @batch.update(batch_params)
        format.html { redirect_to @batch, notice: 'Batch was successfully updated.' }
        format.json { render :show, status: :ok, location: @batch }
      else
        format.html { render :edit }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /batches/1
  # DELETE /batches/1.json
  def destroy
    @batch.destroy
    respond_to do |format|
      format.html { redirect_to batches_url, notice: 'Batch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sending

  end

  def receiving

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_batch
      @batch = Batch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def batch_params
      params.require(:batch).permit(:name, :is_broadcasting)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :verify_authenticity_token

  def send_data
    ActionCable.server.broadcast "broadcast_channel_#{params[:batch]}", message: "<p>#{params[:data]}</p>"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/batches/_form.html.erb
<%= form_with(model: batch, local: true) do |form| %>
  <% if batch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(batch.errors.count, "error") %> prohibited this batch from being saved:</h2>

      <ul>
      <% batch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :batch_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/batches/edit.html.erb
<h1>Editing Batch</h1>

<%= render 'form', batch: @batch %>

<%= link_to 'Show', @batch %> |
<%= link_to 'Back', batches_path %>

app/views/batches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Batches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @batches.each do |batch| %>
      <tr>
        <td><%= batch.name %></td>
        <td><%= link_to 'Show', batch %></td>
        <td><%= link_to 'Edit', edit_batch_path(batch) %></td>
        <td><%= link_to 'Destroy', batch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Batch', new_batch_path %>

app/views/batches/new.html.erb
<h1>New Batch</h1>

<%= render 'form', batch: @batch %>

<%= link_to 'Back', batches_path %>

app/views/batches/receiving.html.erb
<script type="text/javascript" charset="utf-8">
    App.room = App.cable.subscriptions.create({channel:"BroadcastChannel",room: "broadcast_channel_<%=@batch.id%>"}, {
        received: function(data) {
            $('#messages').empty();
            $('#messages').append(data['message']);
        }
    });

    // ---
</script>
<h1>Action Cable Example</h1>

<div id="messages"></div>

app/views/batches/sending.html.erb
<script type="text/javascript" charset="utf-8">
$(document).ready(function(){
    /*
    $('#broadcast_text').keyup(function(){
        var data = $('#broadcast_text').val();
        $.post("/send_data", {data: data})
      });
    */
    setInterval(function(){
        var data = $('#broadcast_text').val();
        var batch = $('#batch_id').val();
        $.post("/send_data", {data: data, batch: batch})
    }, 1000);
});


</script>
<h2>Enter Text</h2>
<%=text_area_tag :broadcast_text, "", style:"width:800px; height:400px;border:2px"%>
<%= hidden_field_tag :batch_id, @batch.id%>

app/views/batches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @batch.name %>
</p>

<p>
  <strong>Is broadcasting:</strong>
  <%= @batch.is_broadcasting %>
</p>

<%= link_to "Start Broadcast", "/batches/#{@batch.id}/sending"%>
<%= link_to "Listen To Broadcast", "/batches/#{@batch.id}/receiving"%>
<br/>
<%= link_to 'Edit', edit_batch_path(@batch) %>
<%= link_to 'Back', batches_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SctAction</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1> Hai </h1>

<%=link_to "Send" , "/sending"%>
<%=link_to "Receive" , "/receiving"%>

app/views/welcome/receiving.html.erb
<script type="text/javascript" charset="utf-8">
    App.room = App.cable.subscriptions.create("BroadcastChannel", {
        received: function(data) {
            $('#messages').empty();
            $('#messages').append(data['message']);
        }
    });
</script>
<h1>Action Cable Example</h1>

<div id="messages"></div>

app/views/welcome/sending.html.erb
<script type="text/javascript" charset="utf-8">
$(document).ready(function(){
    /*
    $('#broadcast_text').keyup(function(){
        var data = $('#broadcast_text').val();
        $.post("/send_data", {data: data})
      });
    */
    setInterval(function(){
        var data = $('#broadcast_text').val();
        $.post("/send_data", {data: data})
    }, 1000);
});


</script>
<h2>Enter Text</h2>
<%=text_area_tag :broadcast_text, "", style:"width:800px; height:400px;border:2px"%>